spring:
  application:
    name: dm-pay-provider
  rabbitmq:
    host: 192.168.92.131
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://192.168.92.131:3306/dm_pay?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
moduleName: pay_provider

---
spring:
  profiles: provider1
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
#       defaultZone: http://root:123456@192.168.92.131:9000/eureka/
#      defaultZone: http://root:123456@discovery:9000/eureka/
      defaultZone: http://root:123456@192.168.92.131:7776/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 7031

---
spring:
  profiles: provider2
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@discovery:7776/eureka/
#      defaultZone: http://root:123456@192.168.92.131:9000/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 7032



